# Generated by Django 6.0.1 on 2026-01-26 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('payload_json', models.TextField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tenants.tenant')),
            ],
            options={
                'db_table': 'events',
                'indexes': [models.Index(fields=['tenant_id', 'created_at'], name='idx_events_tenant_created'), models.Index(fields=['tenant_id', 'type', 'created_at'], name='idx_events_tenant_type_created')],
            },
        ),
    ]
