# Generated by Django 6.0.1 on 2026-01-26 15:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('RETRYABLE_FAILURE', 'Retryable Failure'), ('NON_RETRYABLE_FAILURE', 'Non-Retryable Failure')], max_length=25, null=True)),
                ('classification', models.CharField(blank=True, choices=[('NETWORK_ERROR', 'Network Error'), ('DNS_ERROR', 'DNS Error'), ('TLS_ERROR', 'TLS Error'), ('TIMEOUT', 'Timeout'), ('HTTP_4XX_PERMANENT', 'HTTP 4xx Permanent'), ('HTTP_5XX_RETRYABLE', 'HTTP 5xx Retryable'), ('RATE_LIMITED', 'Rate Limited'), ('WORKER_CRASH_OR_UNKNOWN', 'Worker Crash or Unknown'), ('OTHER', 'Other')], max_length=25, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('response_headers_json', models.JSONField(blank=True, null=True)),
                ('response_body_snippet', models.TextField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('request_payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attempts',
            },
        ),
    ]
