# Generated by Django 6.0.1 on 2026-01-26 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attempts', '0001_initial'),
        ('deliveries', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='deliveries.delivery'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['delivery_id', 'attempt_number'], name='idx_attempts_delivery_num'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('delivery', 'attempt_number'), name='unique_delivery_attempt_number'),
        ),
    ]
