# Generated by Django 6.0.1 on 2026-01-26 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endpoints', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('RELIABLE', 'Reliable'), ('BASIC', 'Basic')], default='RELIABLE', max_length=10)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('idempotency_key_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('attempts_count', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('first_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('terminal_at', models.DateTimeField(blank=True, null=True)),
                ('terminal_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('lease_id', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='endpoints.endpoint')),
            ],
            options={
                'verbose_name_plural': 'deliveries',
                'db_table': 'deliveries',
            },
        ),
    ]
