# Generated by Django 6.0.1 on 2026-01-26 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('events', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='events.event'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['endpoint_id', 'status', 'next_attempt_at'], name='idx_deliveries_worker_lease'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='idx_deliveries_status_next'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['tenant_id', 'endpoint_id', 'idempotency_key_hash'], name='idx_deliveries_dedup'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key_hash__isnull', False)), fields=('tenant_id', 'endpoint_id', 'idempotency_key_hash'), name='unique_delivery_idempotency'),
        ),
    ]
