# Generated by Django 6.0.1 on 2026-02-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='delivery',
            name='unique_delivery_idempotency',
        ),
        migrations.AddField(
            model_name='delivery',
            name='idempotency_key_reused',
            field=models.BooleanField(default=False),
        ),
    ]
