# Generated by Django 6.0.1 on 2026-01-26 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endpoints', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['tenant_id'], name='idx_endpoints_tenant'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['tenant_id', 'status'], name='idx_endpoints_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='endpoint',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tenant_endpoint_name'),
        ),
    ]
