# Generated by Django 6.0.1 on 2026-02-20 00:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0003_add_idempotency_reused_flag'),
        ('endpoints', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='REPLAY', max_length=20)),
                ('dry_run', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('created_deliveries_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('COMPLETED', 'Completed')], default='CREATED', max_length=10)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_batches', to='tenants.apikey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_batches', to='tenants.tenant')),
            ],
            options={
                'db_table': 'delivery_batches',
            },
        ),
        migrations.CreateModel(
            name='DeliveryBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='replays.deliverybatch')),
                ('created_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_replay', to='deliveries.delivery')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_items', to='endpoints.endpoint')),
                ('source_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_items', to='deliveries.delivery')),
            ],
            options={
                'db_table': 'delivery_batch_items',
            },
        ),
    ]
